import { QueryInterface, DataTypes } from "sequelize";

export default {
  up: (queryInterface: QueryInterface) => {
    return queryInterface.bulkInsert("produto", [
      {
        codigo: 1001,
        nome: "X-Burguer",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 10.00,
        quant_pedidos: 230,
      },
      {
        codigo: 1002,
        nome: "X-Salada",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 8.00,
        quant_pedidos: 100,
      },
      {
        codigo: 1003,
        nome: "X-Tudo",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 20.00,
        quant_pedidos: 250,
      },
      {
        codigo: 1004,
        nome: "X-Frango",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 10.00,
        quant_pedidos: 100,
      },
      {
        codigo: 1005,
        nome: "X-Bacon",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 15.00,
        quant_pedidos: 100,
      },
      {
        codigo: 1006,
        nome: "X-Calabresa",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 13.00,
        quant_pedidos: 100,
      },
      {
        codigo: 1007,
        nome: "X-Picanha",
        categoria: "Hamburguer",
        foto: "https://embutidosbonatti.ind.br/temp/xxx-57-1920x1080m1.jpg",
        valor: 30.00,
        quant_pedidos: 160,
      },

      {
        codigo: 1101,
        nome: "Pastel de Queijo",
        categoria: "Pastel",
        foto: "https://img.itdg.com.br/images/recipes/000/020/617/354276/354276_original.jpg",
        valor: 10.00,
        quant_pedidos: 100,
      },
      {
        codigo: 1102,
        nome: "Pastel de Frango",
        categoria: "Pastel",
        foto: "https://img.itdg.com.br/images/recipes/000/020/617/354276/354276_original.jpg",
        valor: 8.00,
        quant_pedidos: 220,
      },
      {
        codigo: 1103,
        nome: "Pastel de Carne",
        categoria: "Pastel",
        foto: "https://img.itdg.com.br/images/recipes/000/020/617/354276/354276_original.jpg",
        valor: 20.00,
        quant_pedidos: 150,
      },
      {
        codigo: 1104,
        nome: "Pastel de Calabresa",
        categoria: "Pastel",
        foto: "https://img.itdg.com.br/images/recipes/000/020/617/354276/354276_original.jpg",
        valor: 10.00,
        quant_pedidos: 190,
      },
      {
        codigo: 1105,
        nome: "Pastel de Camarão",
        categoria: "Pastel",
        foto: "https://img.itdg.com.br/images/recipes/000/020/617/354276/354276_original.jpg",
        valor: 15.00,
        quant_pedidos: 100,
      },

      {
        codigo: 2001,
        nome: "Coca-cola",
        categoria: "Refrigerante",
        foto: "https://www.imigrantesbebidas.com.br/bebida/images/products/full/1984-refrigerante-coca-cola-lata-350ml.jpg",
        valor: 5.00,
        quant_pedidos: 240,
      },
      {
        codigo: 2002,
        nome: "Guarana Antartica",
        categoria: "Refrigerante",
        foto: "https://www.imigrantesbebidas.com.br/bebida/images/products/full/1984-refrigerante-coca-cola-lata-350ml.jpg",
        valor: 5.00,
        quant_pedidos: 210,
      },
      {
        codigo: 2003,
        nome: "Sukita",
        categoria: "Refrigerante",
        foto: "https://www.imigrantesbebidas.com.br/bebida/images/products/full/1984-refrigerante-coca-cola-lata-350ml.jpg",
        valor: 5.00,
        quant_pedidos: 100,
      },
      {
        codigo: 2004,
        nome: "Pepsi",
        categoria: "Refrigerante",
        foto: "https://www.imigrantesbebidas.com.br/bebida/images/products/full/1984-refrigerante-coca-cola-lata-350ml.jpg",
        valor: 5.00,
        quant_pedidos: 100,
      },
      {
        codigo: 2005,
        nome: "Cajuina",
        categoria: "Refrigerante",
        foto: "https://www.imigrantesbebidas.com.br/bebida/images/products/full/1984-refrigerante-coca-cola-lata-350ml.jpg",
        valor: 5.00,
        quant_pedidos: 170,
      },

      {
        codigo: 2101,
        nome: "Heineken",
        categoria: "Cerveja",
        foto:"https://www.imigrantesbebidas.com.br/bebida/images/products/full/222-cerveja-heineken-long-neck-330ml.jpg",
        valor: 8.00,
        quant_pedidos: 200,
      },
      {
        codigo: 2102,
        nome: "Corona",
        categoria: "Cerveja",
        foto:"https://www.imigrantesbebidas.com.br/bebida/images/products/full/222-cerveja-heineken-long-neck-330ml.jpg",
        valor: 8.00,
        quant_pedidos: 100,
      },
      {
        codigo: 2103,
        nome: "Budweiser",
        categoria: "Cerveja",
        foto:"https://www.imigrantesbebidas.com.br/bebida/images/products/full/222-cerveja-heineken-long-neck-330ml.jpg",
        valor: 8.00,
        quant_pedidos: 180,
      },
      {
        codigo: 2104,
        nome: "Stella Artois",
        categoria: "Cerveja",
        foto:"https://www.imigrantesbebidas.com.br/bebida/images/products/full/222-cerveja-heineken-long-neck-330ml.jpg",
        valor: 8.00,
        quant_pedidos: 100,
      },
      {
        codigo: 2105,
        nome: "Guiness",
        categoria: "Cerveja",
        foto:"https://www.imigrantesbebidas.com.br/bebida/images/products/full/222-cerveja-heineken-long-neck-330ml.jpg",
        valor: 10.00,
        quant_pedidos: 100,
      },
      
    ]);
  },
  down: (queryInterface: QueryInterface) => {
    return queryInterface.bulkDelete("produto", {});
  },
};
